### ISSUE TITLE
ChunkedEncodingError while uploading

### ISSUE THREAD

**Issue by sgdave** [StenSipma/astrometry_net_client#38]
Following error appears after a long delay when trying to upload via Client 

File "C:\Users\admin\Anaconda3\envs\PhD\lib\site-packages\requests\models.py", line 754, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(8 bytes read)', IncompleteRead(8 bytes read))

**Comment by StenSipma** [comment]
Thanks for letting me know, could you maybe give some more information about:
- The Python version you are using
- Version of this package
- Version of the requests package
- The image you were trying to upload
- Maybe the code which you were using to upload it

That information will help to narrow down how the issue occurs. Thanks!

**Comment by sgdave** [comment]
Python version 3.7.9
Package version 0.2.4
requests package version 2.28.2
Tried various images, fits, tif, png .. same error for all.

import requests
import json
from astrometry_net_client import Session, FileUpload, Client

Code snippet below
c = Client(api_key=api_key)
job = c.upload_file(file)

**Comment by StenSipma** [comment]
It looks like you are using quite an outdated package since your python version is 3.7.x. Could you maybe try with a newer version of Python and the latest version of the package and see if it works then?

**Comment by sgdave** [comment]
<3
Updated to Python 3.10.10 and worked on first try.
Thank you so much!

**Comment by StenSipma** [comment]
No worries! Hope the package helps a bit :)
