### ISSUE TITLE
upload image in url

### ISSUE THREAD

**Issue by Cathelloya** [StenSipma/astrometry_net_client#54]
I change parts of code so that I can upload local image files and get the url of annotated_display, it seems that I can only upload local image, waht can I do to upload image in url?

```from astrometry_net_client import Session
from astrometry_net_client import FileUpload
s = Session(api_key='******')
upl = FileUpload('1.png', session=s)

submission = upl.submit()
submission.until_done()

job = submission.jobs[0]

if job.success():
    pass
else:
    print('Job failed: {}'.format(job.job_message))

jobid = str(job.id)
addr="http://nova.astrometry.net/annotated_display/" + jobid

job.until_done()

print(addr)```

**Comment by Cathelloya** [comment]
```import os
import requests
from astrometry_net_client import Session
from astrometry_net_client import FileUpload

s = Session(api_key='*****')

url_image = 'https:***'

local_filename = 'local_image.jpg'
response = requests.get(url_image)
with open(local_filename, 'wb') as f:
    f.write(response.content)

upl = FileUpload(local_filename, session=s)

submission = upl.submit()
submission.until_done()

jobid = str(job.id)
addr = "http://nova.astrometry.net/annotated_display/" + jobid

job.until_done()
print(addr)
os.remove(local_filename)
```

I solve it in this way

**Comment by StenSipma** [comment]
There should already be a method on the `Job` class which returns the annotated display as a JPG file: see the [documentation](https://astrometry-net-client.readthedocs.io/en/latest/modules/statusables.html#astrometry_net_client.statusables.Job.annotated_display).

I have not used this method extensively, so I am curious to see if it works for you!

**Comment by StenSipma** [comment]
Update: the newest version (v0.3.1) now also has the [`URLUpload`](https://astrometry-net-client.readthedocs.io/en/latest/modules/uploads.html#astrometry_net_client.uploads.URLUpload) class which you can use directly. This way you don't have to download the file manually!
